// Code generated by goctl. DO NOT EDIT.
package types

type NewEnvRequest struct {
	Config []byte `json:"config"`
}

type NewEnvResponse struct {
	Code string `json:"string"`
}

type CreateRequest struct {
	Caller []byte `json:"caller"`
	Code   []byte `json:"code"`
	Gas    uint64 `json:"gas"`
	Value  []byte `json:"value"`
}

type CreateResponse struct {
	Ret          []byte `json:"ret"`
	ContractAddr []byte `json:"contractAddr"`
	LeftOverGas  uint64 `json:"leftOverGas"`
	Error        string `json:"error"`
}

type CallRequest struct {
	Caller []byte `json:"caller"`
	Addr   []byte `json:"addr"`
	Input  []byte `json:"input"`
	Gas    uint64 `json:"gas"`
	Value  []byte `json:"value"`
}

type CallResponse struct {
	Ret         []byte `json:"ret"`
	LeftOverGas uint64 `json:"leftOverGas"`
	Error       string `json:"error"`
}
