// Code generated by goctl. DO NOT EDIT.
package types

type NewEnvRequest struct {
	Config string `json:"config"`
}

type NewEnvResponse struct {
	Code string `json:"string"`
}

type CreateRequest struct {
	Caller string `json:"caller"`
	Code   string `json:"code"`
	Gas    string `json:"gas"`
	Value  string `json:"value"`
}

type CreateResponse struct {
	Ret          []byte `json:"ret"`
	ContractAddr []byte `json:"contractAddr"`
	LeftOverGas  uint64 `json:"leftOverGas"`
	Error        string `json:"error"`
}

type CallRequest struct {
	Caller string `json:"caller"`
	Addr   string `json:"addr"`
	Input  string `json:"input"`
	Gas    string `json:"gas"`
	Value  string `json:"value"`
}

type CallResponse struct {
	Ret         []byte `json:"ret"`
	LeftOverGas uint64 `json:"leftOverGas"`
	Error       string `json:"error"`
}
