// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"evm-container/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/evm/newEnv",
				Handler: NewEnvHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/evm/create",
				Handler: CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/evm/call",
				Handler: CallHandler(serverCtx),
			},
		},
	)
}
