// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"evm-container/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/evm/newEnv",
				Handler: NewEnvHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/evm/setBlockContext",
				Handler: SetBlockContextHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/evm/reset",
				Handler: ResetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/evm/cancel",
				Handler: CancelHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/evm/cancelled",
				Handler: CancelledHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/evm/chainConfig",
				Handler: ChainConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/evm/create",
				Handler: CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/evm/create2",
				Handler: Create2Handler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/evm/call",
				Handler: CallHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/evm/delegateCall",
				Handler: DelegateCallHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/evm/staticCall",
				Handler: StaticCallHandler(serverCtx),
			},
		},
	)
}
